import { nextui } from "@nextui-org/theme";
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@nextui-org/theme/dist/components/(button|checkbox|divider|input|navbar|select|table|ripple|spinner|listbox|popover|scroll-shadow|spacer).js",
  ],
  theme: {
    extend: {
      colors: {
        light: {
          primary: "#3c6090",
          "surface-tint": "#ffffff",
          "on-primary": "#ffffff",
          "primary-container": "#d4e3ff",
          "on-primary-container": "#001c3a",
          secondary: "#ffffff",
          "on-secondary": "#ffffff",
          "secondary-container": "#ffffff",
          "on-secondary-container": "#ffffff",
          tertiary: "#ffffff",
          "on-tertiary": "#ffffff",
          "tertiary-container": "#ffffff",
          "on-tertiary-container": "#ffffff",
          error: "#ffffff",
          "on-error": "#ffffff",
          "error-container": "#ffffff",
          "on-error-container": "#ffffff",
          background: "#ffffff",
          "on-background": "#ffffff",
          surface: "#f9f9ff",
          "on-surface": "#1a1c20",
          "surface-variant": "#ffffff",
          "on-surface-variant": "#ffffff",
          outline: "#ffffff",
          "outline-variant": "#ffffff",
          shadow: "#ffffff",
          scrim: "#ffffff",
          "inverse-surface": "#ffffff",
          "inverse-on-surface": "#ffffff",
          "inverse-primary": "#ffffff",
          "primary-fixed": "#ffffff",
          "on-primary-fixed": "#ffffff",
          "primary-fixed-dim": "#ffffff",
          "on-primary-fixed-variant": "#ffffff",
          "secondary-fixed": "#ffffff",
          "on-secondary-fixed": "#ffffff",
          "secondary-fixed-dim": "#ffffff",
          "on-secondary-fixed-variant": "#ffffff",
          "tertiary-fixed": "#ffffff",
          "on-tertiary-fixed": "#ffffff",
          "tertiary-fixed-dim": "#ffffff",
          "on-tertiary-fixed-variant": "#ffffff",
          "surface-dim": "#d8dae0",
          "surface-bright": "#f7f9ff",
          "surface-container-lowest": "#ffffff",
          "surface-container-low": "#f2f3fa",
          "surface-container": "#ededf4",
          "surface-container-high": "#e7e8ee",
          "surface-container-highest": "#e1e2e9",
        },
      },
    },
  },
  plugins: [nextui()],
};

export default config;
